[2018-09-26T23:09:36.096] [DEBUG] fbs - brewchain init
[2018-09-26T23:09:36.099] [DEBUG] fbs - brewchain installSmartContract
[2018-09-26T23:11:31.067] [DEBUG] fbs - brewchain init
[2018-09-26T23:11:31.070] [DEBUG] fbs - brewchain installSmartContract
[2018-09-26T23:13:06.623] [DEBUG] fbs - brewchain init
[2018-09-26T23:13:06.626] [DEBUG] fbs - brewchain installSmartContract
[2018-09-26T23:13:07.580] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:07.584] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:07.778] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:07.779] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:07.929] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.220] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.220] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.532] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.532] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.532] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.532] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.532] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.834] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:08.834] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:09.185] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:09.555] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:09.555] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:09.556] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:09.929] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.410] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.410] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.410] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.411] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.411] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.411] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.602] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.602] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:10.756] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.097] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.182] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.182] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.423] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.424] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.508] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.586] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.586] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.889] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:11.914] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.132] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.291] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.329] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.354] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.651] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.683] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.771] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.800] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.800] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:12.961] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:13.688] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:13.736] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:13.769] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:13.862] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:13.890] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:13.918] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:13.981] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.035] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.148] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.180] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.569] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.661] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.695] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.806] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.871] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:14.880] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:15.008] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:15.324] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:15.432] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:15.535] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:15.919] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.000] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.018] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.173] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.500] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.537] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.634] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:14:53.673] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:13:16.679] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.799] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.819] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.931] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:16.943] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:17.432] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:17.471] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:17.520] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:18.095] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:18.769] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:19.660] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:19.779] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:13:20.349] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:15:28.322] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:29.326] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:30.327] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:31.332] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:32.338] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:13:20.616] [INFO] fbs - Submit batches failed, RequestError: Error: getaddrinfo ENOTFOUND ta200.icwv.co ta200.icwv.co:38000
    at new RequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Users/camulos/Documents/java/chaincore/tb/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:185:22)
    at emitOne (events.js:125:13)
    at Request.emit (events.js:221:7)
    at Request.onRequestError (/Users/camulos/Documents/java/chaincore/tb/node_modules/request/request.js:881:8)
    at emitOne (events.js:125:13)
    at ClientRequest.emit (events.js:221:7)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at emitOne (events.js:125:13)
    at Socket.emit (events.js:221:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[2018-09-26T23:15:33.343] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:34.346] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:35.354] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:36.359] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:37.363] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:38.365] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:39.370] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:40.375] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:41.379] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:42.385] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:43.392] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:44.396] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:45.401] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:46.405] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:47.410] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:48.422] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:49.429] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:50.430] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:51.436] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:52.475] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:53.477] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
[2018-09-26T23:15:54.478] [DEBUG] fbs - unhandled_exception:  { Error: spawn ps ENFILE
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  errno: 'ENFILE',
  code: 'ENFILE',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ 'lx' ] }
